### ISSUE TITLE
Selected group inside URL

### ISSUE THREAD

**Issue by lars-sh** [noxone/group-randomizer#12]
The currently selected group shall be present in the URL (via hash) in order to have deep links for each group.

**Comment by noxone** [comment]
Done,

**Comment by noxone** [comment]
@lars-sh Please check!

**Comment by lars-sh** [comment]
noxone, this seems to work for groups without white spaces, while group names with white spaces are visible in the URL, but do not load any group.

Tested with latest iOS Safari.

**Comment by noxone** [comment]
If the group is preselected it seems to be impossible to (de)select group members...
